In [1]:
# Rishant Prakash
# AST 5765: Advanced Astronomical Data Analysis
# Homework 3
# September 2026

import numpy as np
from hw3_prakash_support_functions import square, squareplot


print('Problem 2')

# Problem 2(h): create integers from 0 through 9 and square them.
test_square_1 = np.arange(10)
print('test_square_1 =')
print(test_square_1)
print('square(test_square_1) =')
print(square(test_square_1))

# Problem 2(i): create a 5 x 5 array of floats from 0 through 25.
test_square_2 = np.linspace(0.0, 25.0, 25).reshape(5, 5)
print('test_square_2 =')
print(test_square_2)
print('square(test_square_2) =')
print(square(test_square_2))


print('Problem 3')

# Five evenly spaced values from 1 to 7 are 1, 2.5, 4, 5.5, and 7.
squareplot(1, 7, 5, saveplot='hw3_prakash_problem3_plot.pdf')
print('Saved plot as hw3_prakash_problem3_plot.pdf')


print('Problem 4')
print('The rubric is submitted as hw3_prakash_problem4_rubric.txt.')

Problem 2
test_square_1 =
[0 1 2 3 4 5 6 7 8 9]
square(test_square_1) =
[ 0  1  4  9 16 25 36 49 64 81]
test_square_2 =
[[ 0.          1.04166667  2.08333333  3.125       4.16666667]
 [ 5.20833333  6.25        7.29166667  8.33333333  9.375     ]
 [10.41666667 11.45833333 12.5        13.54166667 14.58333333]
 [15.625      16.66666667 17.70833333 18.75       19.79166667]
 [20.83333333 21.875      22.91666667 23.95833333 25.        ]]
square(test_square_2) =
[[  0.           1.08506944   4.34027778   9.765625    17.36111111]
 [ 27.12673611  39.0625      53.16840278  69.44444444  87.890625  ]
 [108.50694444 131.29340278 156.25       183.37673611 212.67361111]
 [244.140625   277.77777778 313.58506944 351.5625     391.71006944]
 [434.02777778 478.515625   525.17361111 574.00173611 625.        ]]
Problem 3
Saved plot as hw3_prakash_problem3_plot.pdf
Problem 4
The rubric is submitted as hw3_prakash_problem4_rubric.txt.
